### ISSUE TITLE
Keyboard still showing on Android Nexus 9

### ISSUE THREAD

**Issue by dinobu** [masonyc/Xamarin.EnableKeyboardEffect#8] opened 2018-12-05 00:24 UTC
Even after successfuly adding this package and all what is required in XAML Entry, the keyboard is still showing
```
            <Entry x:Name="BarcodeEntry" Text="{Binding BarcodeEntryText}" effects:EnableKeyboardEffect.EnableKeyboard="False" IsVisible="false">
                <Entry.Behaviors>
                    <behaviorsPack:EventToCommandBehavior EventName="Completed" Command="{Binding BarcodeEntryCompletedCommand}" />
                </Entry.Behaviors>
                <Entry.Effects>
                    <effects:KeyboardEnableEffect/>
                </Entry.Effects>
            </Entry>
```

**Comment by masonyc** [comment] 2018-12-05 01:06
Please upload a minimum sample repo. I cant reproduce this problem in nexus 9 emulator.

**Comment by dinobu** [comment] 2018-12-05 01:07
> Please upload a minimum sample repo. I cant reproduce this problem in nexus 9 emulator.

I cannot do that as it is on our project, but I am seeing it on device, havent tried emulator.

**Comment by masonyc** [comment] 2018-12-05 01:11
Don't need your actual project. You can create a sample project that can reproduce this error and not include any business logic inside it.  Also try build nuget sample project in this repo and deploy to your device to see if error still exist.

**Comment by dinobu** [comment] 2018-12-11 00:18
> Don't need your actual project. You can create a sample project that can reproduce this error and not include any business logic inside it. Also try build nuget sample project in this repo and deploy to your device to see if error still exist.

@masonyc  @tmt242001 I think I know what the problem is.  Your solution will not show keyboard if user taps on the Entry field and focuses on it that way.  However, programatic focusing by using MyEntry.Focus() will not work.  Also, this is easily reproducable on devices.  Do you still need a sample project?  Thanks

**Comment by masonyc** [comment] 2018-12-12 04:04
> > Don't need your actual project. You can create a sample project that can reproduce this error and not include any business logic inside it. Also try build nuget sample project in this repo and deploy to your device to see if error still exist.
> 
> @masonyc @tmt242001 I think I know what the problem is. Your solution will not show keyboard if user taps on the Entry field and focuses on it that way. However, programmatic focusing by using `MyEntry.Focus() `will not work.
> 
> In terms of device/Android version, I tried it on
> 
> * Nexus 9 - Android 7.1.1 > **NOT WORKING**.  Your requirement is Android 8.1.  **Is it possible to lower that to Android 7.0?**
> * Galaxy Tab S4 - Android 8.1.0 > **NOT WORKING**.  Not sure why it is not working as the Android version requirement is met here but the keyboard is still showing
> * Pixel - Android 9 > **WORKING**
> 
> Do you still need a sample project? Thanks

Hi, I have fixed it in v1.05. You need to init the effect in android like you did in iOS. However I noticed that there are some funny things happen on tablet devices and can not figure out why.

**Comment by dinobu** [comment] 2018-12-12 16:47
> 
> 
> > > Don't need your actual project. You can create a sample project that can reproduce this error and not include any business logic inside it. Also try build nuget sample project in this repo and deploy to your device to see if error still exist.
> > 
> > 
> > @masonyc @tmt242001 I think I know what the problem is. Your solution will not show keyboard if user taps on the Entry field and focuses on it that way. However, programmatic focusing by using `MyEntry.Focus() `will not work.
> > In terms of device/Android version, I tried it on
> > 
> > * Nexus 9 - Android 7.1.1 > **NOT WORKING**.  Your requirement is Android 8.1.  **Is it possible to lower that to Android 7.0?**
> > * Galaxy Tab S4 - Android 8.1.0 > **NOT WORKING**.  Not sure why it is not working as the Android version requirement is met here but the keyboard is still showing
> > * Pixel - Android 9 > **WORKING**
> > 
> > Do you still need a sample project? Thanks
> 
> Hi, I have fixed it in v1.05. You need to init the effect in android like you did in iOS. However I noticed that there are some funny things happen on tablet devices and can not figure out why.

Thanks, so the "funny" issues are happening on 1.05?  What issues?

Also, why are TabLayoutResource and ToolbarResources needed?  Looks like this is more related to your own playing project and is left in by accident?

Also, looks like Android 8.1 is still required for this to work?

```
        protected override void OnCreate(Bundle savedInstanceState)
        {
            TabLayoutResource = Resource.Layout.Tabbar; //WHY?
            ToolbarResource = Resource.Layout.Toolbar; //WHY?

            base.OnCreate(savedInstanceState);
            global::Xamarin.Forms.Forms.Init(this, savedInstanceState);
            Xamarin.EnableKeyboardEffect.Droid.Effects.Init(this);//need this line to init effect in android
            LoadApplication(new App());
        }
```

**Comment by masonyc** [comment] 2018-12-12 20:02
so the issue is if you focus the entry by code multiple times in a short period(say 5 seconds), the keyboard sometime still pop up. If you dont use virtual keyboard at all in your project, I would suggest you to make a custom control and remove the keyboard all the time for that custom control by doing something like`
                var imm = (InputMethodManager)_activity?.GetSystemService(Context.InputMethodService);
                imm?.HideSoftInputFromWindow(Control.WindowToken, HideSoftInputFlags.None);`.

Android 8.1 is the target framework you use to compile the project, You can still deploy to Android 7.0 device.
![image](https://user-images.githubusercontent.com/18006944/49895595-b42a3200-feb5-11e8-9b49-f06dec5633a7.png)

**Comment by dinobu** [comment] 2018-12-12 21:30
> 
> 
> so the issue is if you focus the entry by code multiple times in a short period(say 5 seconds), the keyboard sometime still pop up. If you dont use virtual keyboard at all in your project, I would suggest you to make a custom control and remove the keyboard all the time for that custom control by doing something like` var imm = (InputMethodManager)_activity?.GetSystemService(Context.InputMethodService); imm?.HideSoftInputFromWindow(Control.WindowToken, HideSoftInputFlags.None);`.
> 
> Android 8.1 is the target framework you use to compile the project, You can still deploy to Android 7.0 device.
> ![image](https://user-images.githubusercontent.com/18006944/49895595-b42a3200-feb5-11e8-9b49-f06dec5633a7.png)

No, that is not the issue.  I explained issue above already.  The issue seam to be related to either one of the 3
- Entry is focused by call to MyEntry.Focus() rather than by tapping on it
- Android version 8.1 or above (however, here as I said, I see it happen even on 8.1 and I asked if you can lover the Android version below 8.1, say 7.0 or so
- You are testing on emulator not on real device - this could be reason why you dont see it

I did not say anything about 5 sec intervals or so, keyboard shows all times

I also did not say that I cannot deploy to below 8.1.  In fact, I explained above I do deploy to 7.1.  But project is build using  Oreo 8.1

![android - keyboard](https://user-images.githubusercontent.com/40807298/49899965-1cbfd300-fe12-11e8-97d9-88017e594716.png)

**Comment by masonyc** [comment] 2018-12-12 21:38
1. MyEntry.Focus() gives you the focus now, but it still has the issue about the 5s interval i talked about.
2. No, it is suggested by Xamarin that you should always use the latest sdk to compile. 

> We recommend that you always compile with the latest available Target Framework version. Doing so provides you with helpful warning messages for any deprecated APIs that might be called by your code. Using the latest Target Framework version is especially important when you use the latest support library releases – each library expects your app to be compiled at that support library's minimum API level or greater.

3. I tested on real phone device, and can focus by code now.

**Comment by dinobu** [comment] 2018-12-12 21:52
> 
> 
>     1. MyEntry.Focus() gives you the focus now, but it still has the issue about the 5s interval i talked about.
> 
>     2. No, it is suggested by Xamarin that you should always use the latest sdk to compile.
> 
> 
> > We recommend that you always compile with the latest available Target Framework version. Doing so provides you with helpful warning messages for any deprecated APIs that might be called by your code. Using the latest Target Framework version is especially important when you use the latest support library releases – each library expects your app to be compiled at that support library's minimum API level or greater.
> 
>     1. I tested on real phone device, and can focus by code now.

Thanks, so if I understand correctly, for #2, you are saying I should build Android project using latest Android SDK which is 9.0 now I believe?  Do I understand it correctly?

And, is there a reason for that 5 second interval between focuses?  Could that be reduced to 1 sec or removed entirely?  I havent tried 1.0.5 version of your lib yet but I do see that could be problem for me.  Tx

**Comment by masonyc** [comment] 2018-12-12 22:08
Yes, you should build the project using 9.0 sdk if you can. I think 5s interval happens is because when you focus the entry by code, android get confused by current window focus. I dont think there is an easy fix for this one. However, as i said before, if your application dont require virtual keyboard at all, a custom control that hides the keyboard all the time will be a better choice.

**Comment by dinobu** [comment] 2018-12-12 22:45
> 
> 
> Yes, you should build the project using 9.0 sdk if you can. I think 5s interval happens is because when you focus the entry by code, android get confused by current window focus. I dont think there is an easy fix for this one. However, as i said before, if your application dont require virtual keyboard at all, a custom control that hides the keyboard all the time will be a better choice.

Actually, I am building using latest but again, havent tried 1.0.5 yet

Also, the problem with hiding keyboard is that in that case, keyboard shows, then it is hidden.  I tried doing this using custom renderer as described here [](https://theconfuzedsourcecode.wordpress.com/2017/05/19/a-keyboard-disabled-entry-control-in-xamarin-forms/)  That makes it worse, each time Entry receives focus, keyboard shows briefly, then it is hidden.  It is actually you who replied to that attempt and suggested using this library at SO here [](https://stackoverflow.com/questions/53490262/xamarin-forms-entry-that-should-not-show-softkeyboard-on-its-focus/53507220?noredirect=1#comment93927674_53507220)

**Comment by masonyc** [comment] 2018-12-12 22:56
If you are going to toggle the show/hide keyboard status, then effect will suit better than custom control. But if you dont want virtual keyboard at all, then custom control is better. If I remember correctly, do the hide keyboard in ElementChange method then it will hides the keyboard all the time.

**Comment by dinobu** [comment] 2018-12-12 23:46
> 
> 
> If you are going to toggle the show/hide keyboard status, then effect will suit better than custom control. But if you dont want virtual keyboard at all, then custom control is better. If I remember correctly, do the hide keyboard in ElementChange method then it will hides the keyboard all the time.

I dont know if you saw my reply above, but that is exactly what I did.  And I dont want to hide but **prevent** it from showing on that Entry field.  See my previous reply and try it yourself and you will see, I provided link to the article explaining how to do exactly what you are suggesting, it is short and simple but not working.  It was the reason I asked about this on SO and you replied suggesting using your library, again, links to both these are in my comment right above your last reply.

**Comment by masonyc** [comment] 2018-12-12 23:49
> > If you are going to toggle the show/hide keyboard status, then effect will suit better than custom control. But if you dont want virtual keyboard at all, then custom control is better. If I remember correctly, do the hide keyboard in ElementChange method then it will hides the keyboard all the time.
> 
> I dont know if you saw my reply above, but that is exactly what I did. And I dont want to hide but **prevent** it from showing on that Entry field. See my previous reply and try it yourself and you will see, I provided link to the article explaining how to do exactly what you are suggesting, it is short and simple but not working. It was the very reason I asked about this on SO and you replied suggesting using your library so I started looking into it and created this bug, again, links to both these are in my comment right above your last reply.

In your link it is doing hide keyboard through OnPropertyChanging. Hide it without going through this should prevent keyboard completely.

**Comment by dinobu** [comment] 2018-12-13 23:31
> > > If you are going to toggle the show/hide keyboard status, then effect will suit better than custom control. But if you dont want virtual keyboard at all, then custom control is better. If I remember correctly, do the hide keyboard in ElementChange method then it will hides the keyboard all the time.
> > 
> > 
> > I dont know if you saw my reply above, but that is exactly what I did. And I dont want to hide but **prevent** it from showing on that Entry field. See my previous reply and try it yourself and you will see, I provided link to the article explaining how to do exactly what you are suggesting, it is short and simple but not working. It was the very reason I asked about this on SO and you replied suggesting using your library so I started looking into it and created this bug, again, links to both these are in my comment right above your last reply.
> 
> In your link it is doing hide keyboard through OnPropertyChanging. Hide it without going through this should prevent keyboard completely.

Nope, that is not even hiding it then

  ```
  public class EntryWithoutSoftKeyboardRenderer : EntryRenderer
    {
        private readonly Context context;

        public EntryWithoutSoftKeyboardRenderer(Context context) : base(context)
        {
            this.context = context;
        }

        protected override void OnElementChanged(ElementChangedEventArgs<Entry> e)
        {
            base.OnElementChanged(e);

            this.Control.ShowSoftInputOnFocus = false;

            InputMethodManager imm = (InputMethodManager)this.Context.GetSystemService(Context.InputMethodService);
            imm?.HideSoftInputFromWindow(this.Control.WindowToken, 0);
        }
    }
}
```

**Comment by dinobu** [comment] 2018-12-20 01:03
Tried latest version v.1.0.5 built using latest Android SDK (9).  The keyboard is not being prevented from showing up but instead shows, then hides resulting in brief soft keyboard popups.  This is opposite from what this solution claims to do which is to prevent keyboard from showing up entirely.

Tested on Nexus 9 tablet, Android 7.1.1

**Comment by masonyc** [comment] 2019-02-01 01:37
Close this as currently there is no way to guarantee keyboard will hide properly when focus by code in android without Xamarin's change

**Closed by masonyc** 2019-02-01 01:37 UTC
Labels: bug

**Comment by dinobu** [comment] 2019-04-25 23:04
> Close this as currently there is no way to guarantee keyboard will hide properly when focus by code in android without Xamarin's change

So, if I understand correctly, you are saying that tag 2.03 fixes this issue?

**Comment by masonyc** [comment] 2019-04-25 23:09
It still shows the keyboard first if you call focus by code, but it will hide the keyboard after popping up. Please check the sample application.

**Comment by dinobu** [comment] 2019-04-25 23:16
> It still shows the keyboard first if you call focus by code, but it will hide the keyboard after popping up. Please check the sample application.

That means it is hiding, not preventing keyboard to show then.  That effect is even more of an issue because now every time programmatically an Entry field is focused (and in my case, this can happen every second and is often the case), the keyboard will pop up then disappear. :(
